var CTE_LOAD_INIT = 0;
var CTE_RESP_VAL_LOGIN;

var CTE_JSON_USUARIOWEB;
var CTE_JSON_PERFIL;
var CTE_JSON_COURIER;
var CTE_JSON_TERCERO;

var CTE_INIT_IDROL_ADMIN_WS;
var CTE_INIT_IDROL_COLAB_BBVA;
var CTE_INIT_IDROL_COLAB_COURIER;
var CTE_INIT_IDROL_ADMIN_WEB;
var CTE_INIT_STSREGISTRO_ACTIVO		= 1;
var CTE_INIT_STSREGISTRO_INACTIVO	= 0;

var CTE_INIT_PERFILES;
var CTE_INIT_COURIERS;
var CTE_INIT_PARAM_ESTADO;
var CTE_INIT_PARAM_TIPDOCUMENTO;