var CTE_RESP_VAL_LOGIN;
var USR_STS_ACTIVO				= "A";
var USR_STS_INACTIVO			= "I";
var USR_STS_RENOVAR_PASSWORD	= "R";

var CTE_JSON_USUARIOWEB;
var CTE_JSON_PERFIL;
var CTE_JSON_COURIER;
var CTE_JSON_TERCERO;